### ISSUE TITLE
LS -Wide (feature request)

### ISSUE THREAD

**Issue by fdncred** [Davlind/PSColor#14]
Any chance on adding a colored LS-Wide similar to this [one](https://github.com/pecigonzalo/Oh-My-Posh/blob/master/plugins/ls/ls.ps1)?

Thanks,
Darren

**Comment by anthony-brien** [comment]
Would love this to, as that's where colour are most useful, when your list is compact and you just see the names.

**Comment by joonro** [comment]
I maintain [Get-ChildItemColor](https://github.com/joonro/Get-ChildItemColor) which contains `Get-ChildItemColorFormatWide`, which should do what you want, except it does not support pipeline. You can just alias `Get-ChildItemColorFormatWide` to `ls`, and use it separately from `Get-ChildItem`.

**Comment by fdncred** [comment]
@joonro Been using it for a while. Thanks!
