### ISSUE TITLE
publish to powershellgallery

### ISSUE THREAD

**Issue by fredericrous** [Davlind/PSColor#2]
would be great to see this module on https://www.powershellgallery.com
on windows10 we Import-Module(s) without PSget.

**Comment by Davlind** [comment]
Thanks for the suggestion! I've now added it.

https://www.powershellgallery.com/packages/PSColor/1.0.0.0

**Comment by fredericrous** [comment]
Great! Thanks Davlind!!
Note you can add tags to the module in order for others to find it faster on powershellgallery. You can do this in PSColor's manifest (psd1) with field PrivateData. (5 days ago I didn't know about that, I myself published my first module 3 days ago)

here's what is in my manifest file

```
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('perforce','git', 'versioning', 'autocomplete', 'prompt')

        # A URL to the license for this module.
        LicenseUri = 'https://opensource.org/licenses/MS-PL'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/Zougi/posh-p4'

    } # End of PSData hashtable

} # End of PrivateData hashtable
```

**Comment by WestXu** [comment]
Hi @Davlind , I happened to notice that the version on psgallery is still 1.0.0 and last updated at 2016/3/2. Does it mean it's 2-year commits behind the repo?
