### ISSUE TITLE
Clearing console adds an empty line before Prompt()

### ISSUE THREAD

**Issue by brunovieira97** [Davlind/PSColor#24]
When using `clear`, PSColor adds an empty line on first row of terminal window, making the Prompt function start at the second line.

I took a look at the code and the root cause seems to be at **PSColor.psm1@57**:
![image](https://user-images.githubusercontent.com/19749621/82766255-ee5e6980-9df3-11ea-80c7-2008373a23c0.png)

There's a `Write-Host ""` that inserts the empty line.

**My console with said `Write-Host` (original code):**
![image](https://user-images.githubusercontent.com/19749621/82766281-1ea60800-9df4-11ea-8905-03ddeb6c4015.png)

**My console with line 57 commented:**
![image](https://user-images.githubusercontent.com/19749621/82766300-5319c400-9df4-11ea-9b6f-cc81e0a736b2.png)

I'm not very skilled in PowerShell, so my Issue is basically for asking: is line 57 necessary? I removed it and nothing seemed to break.

**Comment by rafaeloledo** [comment]
I'd the same problem. This change could be merged?

**Comment by brunovieira97** [comment]
@rafaeloledo I forked this project a while ago, and **this** issue is fixed on my version. Seems like this project is not maintained anymore.

Ironically though, for the last year or so, I have been using zsh on macOS. Haven't been able to give this project as much attention as I wanted, but I'm planning to go back to it soon.

https://github.com/brunovieira97/ps-color
